# Generated by Django 3.1.4 on 2020-12-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paper', models.CharField(default='', max_length=1000, unique=True)),
                ('titulo', models.CharField(default='', max_length=1000)),
                ('keywords', models.CharField(default='', max_length=10000)),
                ('abstract', models.CharField(default='', max_length=10000000)),
            ],
        ),
    ]
